### ISSUE TITLE
Error gulp deploy

### ISSUE THREAD

**Issue by menteri-bashid** [bashidorg/apps-core#2]
https://github.com/bashidorg/apps-core/blob/47fb4ce883f81ec489d0c72e3a7c02ffba92df7d/bashid-deploy.sh#L51

https://github.com/bashidorg/apps-core/blob/47fb4ce883f81ec489d0c72e3a7c02ffba92df7d/bashid-deploy.sh#L58

**Comment by bhrdn** [comment]
3d3bdac0039cd4b516ac4b37334bbe1463c78d93 :heart:
